BEGIN;
-- PRE-GO-LIVE failed-install uninstall only.
DROP VIEW IF EXISTS retail.effective_compiled_search_jobs;
DROP TABLE IF EXISTS retail.r1c_certification_runs;
DROP TRIGGER IF EXISTS trg_r1c_audit_compilations ON retail.search_job_compilations;
DROP TRIGGER IF EXISTS trg_r1c_audit_compilers ON retail.search_compiler_versions;
DROP TRIGGER IF EXISTS trg_r1c_audit_profiles ON retail.search_route_compile_profiles;
DROP TRIGGER IF EXISTS trg_r1c_compilation_guard ON retail.search_job_compilations;
DROP TRIGGER IF EXISTS trg_r1c_compiler_guard ON retail.search_compiler_versions;
DROP TRIGGER IF EXISTS trg_r1c_compile_profile_guard ON retail.search_route_compile_profiles;
DROP FUNCTION IF EXISTS retail_audit.r1c_log_retail_change();
DROP FUNCTION IF EXISTS retail.r1c_assert_runtime_compiler(uuid,text,text);
DROP FUNCTION IF EXISTS retail.r1c_create_compile_profile(uuid,text,jsonb,jsonb,text);
DROP FUNCTION IF EXISTS retail.r1c_latest_certification_is_current(uuid);
DROP FUNCTION IF EXISTS retail.r1c_assert_runtime_release(uuid,text);
DROP FUNCTION IF EXISTS retail.r1c_certify_compiler(uuid,text,uuid,text,text);
DROP FUNCTION IF EXISTS retail.r1c_compilation_is_current(uuid);
DROP FUNCTION IF EXISTS retail.r1c_compile_route(uuid,uuid,uuid,uuid,text,text);
DROP FUNCTION IF EXISTS retail.r1c_adapter_payload_document(uuid,uuid);
DROP FUNCTION IF EXISTS retail.r1c_normalized_job_document(uuid,uuid);
DROP FUNCTION IF EXISTS retail.r1c_compiler_authority_document(retail.search_compiler_versions);
DROP FUNCTION IF EXISTS retail.r1c_function_sha256(regprocedure);
DROP FUNCTION IF EXISTS retail.r1c_build_query(text,text,jsonb);
DROP FUNCTION IF EXISTS retail.r1c_validate_input_contract(jsonb,text,jsonb);
DROP FUNCTION IF EXISTS retail.r1c_compile_profile_guard();
DROP FUNCTION IF EXISTS retail.r1c_compile_profile_document(retail.search_route_compile_profiles);
DROP FUNCTION IF EXISTS retail.r1c_r1b_binding_is_current();
DROP FUNCTION IF EXISTS retail.r1c_sha256_jsonb(jsonb);
DROP FUNCTION IF EXISTS retail.r1c_sha256_text(text);
DROP TABLE IF EXISTS retail.search_job_compilations;
DROP TABLE IF EXISTS retail.search_compiler_versions;
DROP TABLE IF EXISTS retail.search_route_compile_profiles;
DROP TABLE IF EXISTS retail.r1c_r1b_certification_binding;
DROP TABLE IF EXISTS retail.r1c_schema_state;
COMMIT;
