BEGIN;
INSERT INTO retail.retail_platforms(platform_code,platform_name,base_url,access_type,status,priority_rank,is_purchase_supported,is_data_collection_supported,max_daily_requests,max_hourly_requests,robots_policy_url,terms_url,governance_notes)
SELECT 'amazon','Amazon','https://www.amazon.com',access_type,status,5,true,true,5000,500,'https://www.amazon.com/robots.txt','https://www.amazon.com/gp/help/customer/display.html?nodeId=508088','Bright Data Amazon product dataset gd_l7q7dkf244hwjntr0 using keyword discovery. Web Unlocker zones tcds_web_unlocker and tcds_premium_unlocker are controlled fallback/evidence paths.' FROM retail.retail_platforms ORDER BY created_at LIMIT 1
ON CONFLICT(platform_code) DO UPDATE SET platform_name=EXCLUDED.platform_name,base_url=EXCLUDED.base_url,is_data_collection_supported=true,governance_notes=EXCLUDED.governance_notes,updated_at=now();
DO $$ BEGIN IF NOT EXISTS(SELECT 1 FROM retail.retail_platforms WHERE platform_code='amazon') THEN RAISE EXCEPTION 'Cannot seed Amazon: retail.retail_platforms has no row from which enum values can be copied'; END IF; END $$;
INSERT INTO retail.platform_collection_configs(platform_id,config_name,is_active,schedule_cron,collection_strategy,category_seed_json,search_seed_json,request_policy_json,parser_policy_json,evidence_policy_json)
SELECT id,'Amazon Bright Data keyword discovery ingest v1',true,NULL,'dataset_keyword_discovery_with_unlocker_fallback','[]'::jsonb,'[{"keyword":"smart watch","zipcode":""},{"keyword":"laptops","zipcode":""},{"keyword":"iphone","zipcode":""}]'::jsonb,'{"dataset_id":"gd_l7q7dkf244hwjntr0","type":"discover_new","discover_by":"keyword","limit_per_input":1000,"retryable_http_statuses":[408,425,429,500,502,503,504],"max_attempts":6}'::jsonb,'{"parser_version":"brightdata_amazon_v1","identity_key":"asin","reject_missing_asin":true,"reject_missing_title":true,"reject_missing_price":false,"missing_price_action":"preserve_product_withhold_offer_and_log_dq","sponsored_action":"preserve_and_flag","frequently_returned_action":"preserve_and_flag_high_risk"}'::jsonb,'{"unlocker_mode":"fallback","zones":["tcds_web_unlocker","tcds_premium_unlocker"],"retain_html":true}'::jsonb FROM retail.retail_platforms WHERE platform_code='amazon' AND NOT EXISTS(SELECT 1 FROM retail.platform_collection_configs c WHERE c.platform_id=retail.retail_platforms.id AND c.config_name='Amazon Bright Data keyword discovery ingest v1');
CREATE UNIQUE INDEX IF NOT EXISTS ux_raw_product_capture_idempotency ON retail.raw_product_captures(platform_id,platform_product_key,payload_hash);
CREATE UNIQUE INDEX IF NOT EXISTS ux_retail_products_platform_product ON retail.retail_products(platform_id,platform_product_key);
CREATE UNIQUE INDEX IF NOT EXISTS ux_offer_platform_hash ON retail.retail_offer_snapshots(platform_id,offer_hash);
CREATE UNIQUE INDEX IF NOT EXISTS ux_ingest_dead_letters_source_payload ON retail.ingest_dead_letters(source_platform,payload_hash);
CREATE INDEX IF NOT EXISTS ix_ingest_dlq_retry ON retail.ingest_dead_letters(status,next_retry_at) WHERE status IN ('pending','retrying');
CREATE TABLE IF NOT EXISTS retail.amazon_product_parsed(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),raw_capture_id uuid NOT NULL UNIQUE REFERENCES retail.raw_product_captures(id),collection_run_id uuid REFERENCES retail.collection_runs(id),platform_id uuid NOT NULL REFERENCES retail.retail_platforms(id),source_platform text NOT NULL DEFAULT 'amazon' CHECK(source_platform='amazon'),asin text NOT NULL CHECK(asin ~ '^[A-Za-z0-9]{10}$'),parent_asin text,url text NOT NULL,title text NOT NULL,normalized_title text GENERATED ALWAYS AS(lower(btrim(title))) STORED,brand text,manufacturer text,model_number text,upc text,description text,department text,categories jsonb NOT NULL DEFAULT '[]',root_bs_category text,bs_category text,initial_price numeric(14,2),final_price numeric(14,2),final_price_high numeric(14,2),effective_price numeric(14,2),currency_code char(3) NOT NULL DEFAULT 'USD',availability text,is_available boolean,seller_name text,buybox_seller text,seller_id text,number_of_sellers integer,ships_from text,amazon_prime boolean,amazon_choice boolean,sponsored boolean,coupon jsonb,coupon_description text,discount jsonb,rating numeric(3,2),reviews_count integer,root_bs_rank integer,bs_rank integer,bought_past_month integer,bought_past_month_text text,image_url text,images jsonb NOT NULL DEFAULT '[]',features jsonb NOT NULL DEFAULT '[]',product_details jsonb NOT NULL DEFAULT '[]',variations jsonb,variation_values jsonb,delivery jsonb,other_sellers_prices jsonb,prices_breakdown jsonb,max_quantity_available integer,return_policy text,is_high_price boolean,is_frequently_returned_item_badge boolean,frequently_returned_item_message text,raw_payload jsonb NOT NULL,payload_hash text NOT NULL,source_dataset text NOT NULL DEFAULT 'brightdata_amazon',parser_version text NOT NULL DEFAULT 'brightdata_amazon_v1',parsed_at timestamptz NOT NULL DEFAULT now(),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(platform_id,asin,payload_hash));
CREATE INDEX IF NOT EXISTS ix_amazon_asin_latest ON retail.amazon_product_parsed(asin,parsed_at DESC);
CREATE INDEX IF NOT EXISTS ix_amazon_parent_asin ON retail.amazon_product_parsed(parent_asin) WHERE parent_asin IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_amazon_upc ON retail.amazon_product_parsed(upc) WHERE upc IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_amazon_price_availability ON retail.amazon_product_parsed(effective_price,availability) WHERE effective_price IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_amazon_rank ON retail.amazon_product_parsed(root_bs_rank,bs_rank);
CREATE INDEX IF NOT EXISTS ix_amazon_payload_gin ON retail.amazon_product_parsed USING gin(raw_payload);
CREATE TABLE IF NOT EXISTS retail.amazon_product_images(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),amazon_parsed_id uuid NOT NULL REFERENCES retail.amazon_product_parsed(id) ON DELETE CASCADE,image_url text NOT NULL,image_rank integer NOT NULL CHECK(image_rank>=1),is_main boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(amazon_parsed_id,image_url));
CREATE TABLE IF NOT EXISTS retail.amazon_product_categories(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),amazon_parsed_id uuid NOT NULL REFERENCES retail.amazon_product_parsed(id) ON DELETE CASCADE,category_rank integer NOT NULL CHECK(category_rank>=1),category_name text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(amazon_parsed_id,category_rank));
CREATE TABLE IF NOT EXISTS retail.amazon_product_details(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),amazon_parsed_id uuid NOT NULL REFERENCES retail.amazon_product_parsed(id) ON DELETE CASCADE,detail_rank integer NOT NULL CHECK(detail_rank>=1),detail_type text NOT NULL,detail_value text,normalized_detail_type text GENERATED ALWAYS AS(lower(btrim(detail_type))) STORED,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(amazon_parsed_id,detail_rank));
CREATE INDEX IF NOT EXISTS ix_amazon_details_type_value ON retail.amazon_product_details(normalized_detail_type,detail_value);
CREATE TABLE IF NOT EXISTS retail.amazon_unlocker_evidence(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),collection_run_id uuid REFERENCES retail.collection_runs(id),platform_id uuid NOT NULL REFERENCES retail.retail_platforms(id),target_url text NOT NULL,unlocker_zone text NOT NULL CHECK(unlocker_zone IN ('tcds_web_unlocker','tcds_premium_unlocker')),content_type text,response_status integer NOT NULL DEFAULT 200,content_hash text NOT NULL UNIQUE,response_body text NOT NULL,captured_at timestamptz NOT NULL DEFAULT now(),evidence_metadata jsonb NOT NULL DEFAULT '{}');
CREATE INDEX IF NOT EXISTS ix_amazon_unlocker_url_time ON retail.amazon_unlocker_evidence(target_url,captured_at DESC);
COMMIT;
