server {
    listen 8089;
    server_name _;

    root /srv/pqp/owned-target/public;
    index index.html;

    access_log /var/log/nginx/pqp-owned-target-access.log;
    error_log /var/log/nginx/pqp-owned-target-error.log;

    location / {
        try_files $uri $uri/ =404;
    }
}
