route:
  group_by: ['alertname','component']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: tcds-operations
  routes:
  - matchers: ['severity="critical"']
    receiver: tcds-critical
  - matchers: ['severity="high"']
    receiver: tcds-operations
receivers:
- name: tcds-critical
- name: tcds-operations
