import fs from 'node:fs/promises'; import path from 'node:path'; import { config } from './config.js'; import { log } from './log.js'; import { triggerDataset,waitForSnapshot,downloadSnapshot } from './brightdata.js'; import { CrutchfieldRecordSchema } from './types.js'; import { platformAndConfig,createRun,finishRun,deadLetter,ingestRecord,saveEvidence,pool } from './db.js'; import { isCrutchfieldUrl,sha256,stableJson } from './util.js'; import { unlockCrutchfieldPage } from './unlocker.js';
async function localDlq(payload:unknown,code:string,error:unknown){await fs.mkdir(config.DLQ_DIRECTORY,{recursive:true});await fs.writeFile(path.join(config.DLQ_DIRECTORY,`${Date.now()}-${code}-${sha256(stableJson(payload)).slice(0,12)}.json`),JSON.stringify({ts:new Date().toISOString(),code,error:String(error),payload},null,2));}
async function mapLimit<T>(items:T[],limit:number,fn:(x:T)=>Promise<void>){let i=0;await Promise.all(Array.from({length:Math.min(limit,items.length)},async()=>{while(true){const n=i++;if(n>=items.length)return;await fn(items[n]!);}}));}
async function main(){
 const badUrl=config.seedUrls.find(u=>!isCrutchfieldUrl(u));if(badUrl)throw new Error(`Rejected non-Crutchfield seed URL: ${badUrl}`);
 const {platformId,configId}=await platformAndConfig();const runKey=`crutchfield:${new Date().toISOString().slice(0,13)}:${sha256(config.seedUrls.join('|')).slice(0,12)}`;let runId='';const stats={collected:0,failed:0,skipped:0};
 try{runId=await createRun(platformId,configId,runKey,config.seedUrls);log('info','crutchfield_run_started',{runId,urls:config.seedUrls});
  if(config.CRUTCHFIELD_UNLOCKER_MODE==='always')for(const url of config.seedUrls){const ev=await unlockCrutchfieldPage(url);await saveEvidence(platformId,runId,url,ev.zone,ev.body,ev.contentType,ev.status,{phase:'preflight',page_not_found:ev.pageNotFound});}
  const snapshotId=await triggerDataset(config.seedUrls);log('info','dataset_triggered',{runId,snapshotId});await waitForSnapshot(snapshotId);const rows=await downloadSnapshot(snapshotId);log('info','snapshot_downloaded',{runId,snapshotId,rows:rows.length});
  await mapLimit(rows,config.INGEST_CONCURRENCY,async raw=>{const p=CrutchfieldRecordSchema.safeParse(raw);if(!p.success){stats.failed++;await deadLetter(platformId,runId,raw,'VALIDATION_ERROR',p.error.message);await localDlq(raw,'VALIDATION_ERROR',p.error);return;}try{await ingestRecord(platformId,runId,p.data);stats.collected++;}catch(e){stats.failed++;await deadLetter(platformId,runId,p.data,'INGEST_ERROR',String(e));await localDlq(p.data,'INGEST_ERROR',e);if(config.CRUTCHFIELD_UNLOCKER_MODE==='fallback'){try{const ev=await unlockCrutchfieldPage(p.data.url);await saveEvidence(platformId,runId,p.data.url,ev.zone,ev.body,ev.contentType,ev.status,{phase:'fallback',ingest_error:String(e),page_not_found:ev.pageNotFound});}catch(ue){await deadLetter(platformId,runId,{url:p.data.url,original:p.data},'UNLOCKER_FALLBACK_ERROR',String(ue));}}}});
  if(rows.length===0){for(const url of config.seedUrls){try{const ev=await unlockCrutchfieldPage(url);await saveEvidence(platformId,runId,url,ev.zone,ev.body,ev.contentType,ev.status,{phase:'empty_snapshot_validation',page_not_found:ev.pageNotFound});}catch(e){await deadLetter(platformId,runId,{url},'EMPTY_SNAPSHOT_AND_UNLOCKER_FAILURE',String(e));}}}
  await finishRun(runId,'completed',stats);log('info','crutchfield_run_completed',{runId,...stats});
 }catch(e){if(runId)await finishRun(runId,'failed',stats,String(e));log('error','crutchfield_run_failed',{runId,error:String(e),...stats});throw e;}finally{await pool.end();}
}
main().catch(()=>process.exitCode=1);
